spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    path: /swagger.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true

jwt:
  secret: Z9AeK9oKuYJMAEgZPkr99JYEkNZ15gYzpbSoVzV68d4
  access-token-validity-ms: 1800000      # 30분
  refresh-token-validity-ms: 1209600000  # 14일
  temp-token-validity-ms: 600000         # 10분

aes:
  secret: ahcxprF8G07ogIWhZ/Lp+VmEM7AvosI8rmhQunuKrkM=
  init-vector: a1ze0V5ye2iz4fc7apFk/w==

oauth:
  google:
    client-id: ${OAUTH_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID:CHANGE_ME_KAKAO_CLIENT_ID}
    client-secret: ${OAUTH_KAKAO_CLIENT_SECRET:CHANGE_ME_KAKAO_CLIENT_SECRET}
  naver:
    client-id: ${OAUTH_NAVER_CLIENT_ID:CHANGE_ME_NAVER_CLIENT_ID}
    client-secret: ${OAUTH_NAVER_CLIENT_SECRET:CHANGE_ME_NAVER_CLIENT_SECRET}

redis:
  host: ${REDIS_URL}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

app:
  log:
    dir: /Users/kyu/docker/spring-boot/logs
    level: INFO
    max-history: 30

server:
  forward-headers-strategy: framework