spring:
  config:
    activate:
      on-profile: local
  application:
    name: spring-boot-kotlin-practice

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    path: /swagger.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true

jwt:
  secret: Z9AeK9oKuYJMAEgZPkr99JYEkNZ15gYzpbSoVzV68d4
  access-token-validity-ms: 1800000      # 30분
  refresh-token-validity-ms: 1209600000  # 14일
  temp-token-validity-ms: 600000         # 10분

aes:
  secret: ahcxprF8G07ogIWhZ/Lp+VmEM7AvosI8rmhQunuKrkM=
  init-vector: a1ze0V5ye2iz4fc7apFk/w==

oauth:
  google:
    client-id: ${OAUTH_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID:CHANGE_ME_KAKAO_CLIENT_ID}
    client-secret: ${OAUTH_KAKAO_CLIENT_SECRET:CHANGE_ME_KAKAO_CLIENT_SECRET}
  naver:
    client-id: ${OAUTH_NAVER_CLIENT_ID:CHANGE_ME_NAVER_CLIENT_ID}
    client-secret: ${OAUTH_NAVER_CLIENT_SECRET:CHANGE_ME_NAVER_CLIENT_SECRET}

toss:
  payments:
    secret-key: ${TOSS_PAYMENTS_SECRET_KEY:CHANGE_ME_TOSS_SECRET_KEY}

redis:
  host: ${REDIS_URL}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

app:
  swagger:
    server-url: https://hkh7670.duckdns.org
  log:
    dir: ./logs
    level: INFO
    max-history: 7

server:
  port: 16000